
  parms:
    $FilePrefix : FDMD.FISCALDATA,
    $Stack : S_stack
    $GlueDbName : $Stack-top-fiscaldata
    $SYS : FISCALDATA
    


  EventRuleFDMDxFISCALDATA:
    Type: AWS::Events::Rule
    Properties: 
      Name: !Join [ '-', [ !Ref 'AWS::StackName', "FDMD.FISCALDATA" ]]
      Description: Inbound ZIP file containing FiscalData extracts
      EventPattern: 
        source:
        - aws.s3
        detail-type:
        - Object Created
        detail:
          bucket:
            name:
            - !Join [ '-', [ !Ref 'AWS::StackName', "landing-pad" ]]
          object:
            key:
            - prefix: FISCALDATA/Inbound/FDMD.FISCALDATA      
      #RoleArn: String
      #ScheduleExpression: String
      State: ENABLED
      Targets: 
        - Arn: !GetAtt [ LambdaProcessInitiatorFunction , Arn ]
          Id: ExecBatchInitiatorFunction1
          #RoleArn: tbd
          InputTransformer:
            InputPathsMap:
              "detail-bucket-name": "$.detail.bucket.name"
              "detail-object-key": "$.detail.object.key"
              "source": "$.source" 
            InputTemplate: |
              {
                "source": "<source>",
                "detail": {
                  "bucket": {
                    "name": "<detail-bucket-name>"
                  },
                  "object": {
                    "key": "<detail-object-key>"
                  }
                },
                "batch_parms": {
                  "GlueDatabaseName": "daab-lab-fp5a-top-fiscaldata",
                  "S3OutputBucket": "daab-lab-fp5a-datalake",
                  "S3OutputFolder": "FISCALDATA/PARQUET",
                  "StepFnArn": "arn:aws:states:us-east-2:442483223120:stateMachine:daab-lab-Extract_ZIP_to_Parquet"
                }
              }
